### ISSUE TITLE
Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference

### ISSUE THREAD

**Issue by donenoyes** [16arpi/Fox-RSS#1]
After adding a RSS `https://medium.com/feed/androiddevelopers` and going back to the articles tab, the app crashes with the following trace:

```
2021-04-14 16:45:07.436 15274-15274/com.pigeoff.rss E/RecyclerView: No adapter attached; skipping layout
2021-04-14 16:45:07.558 15274-15274/com.pigeoff.rss E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.pigeoff.rss, PID: 15274
    java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
        at java.io.StringReader.<init>(StringReader.java:50)
        at android.text.HtmlToSpannedConverter.convert(Html.java:748)
```

**Comment by 16arpi** [comment]
Thank for the alert, the bug is fixed ! Please check out [RSS v1.1.1](https://github.com/16arpi/Fox-RSS/releases/tag/v1.1.1) :)
